global PLL_LASTRNG 4
global LAST_PLL_N 16
global LAST_PLL_DIR /Users/xabajian/Documents/GitHub/ACF_NK_Measurement/scripts/
global LAST_PLL_ID rjku5o3ah3
global PLL_STATA_PATH "/Applications/Stata/StataSE.app/Contents/MacOS/stata-se"
global PLL_CHILDREN 16
global PLL_CLUSTERS 16
global USE_PROCEXEC 2
global sim_dir /Users/xabajian/Documents/GitHub/ACF_NK_Measurement/simulations
global processed /Users/xabajian/Documents/GitHub/ACF_NK_Measurement/processed
global raw /Users/xabajian/Documents/GitHub/ACF_NK_Measurement/raw
global tables /Users/xabajian/Documents/GitHub/ACF_NK_Measurement/tables
global figs /Users/xabajian/Documents/GitHub/ACF_NK_Measurement/figs
global root /Users/xabajian/Documents/GitHub/ACF_NK_Measurement
global T_gm_fix_span 1
global S_StataSE SE
